version: '3.8'
services:
    frontend:
      build:
        context: .
        dockerfile: Dockerfile
      image: abatan/books:1
      container_name: front-book
      restart: always
      depends_on:
        - mongodb
      ports:
        - 3000:80
      
    mongodb:
      image: mongo:latest
      # ports:
      #   - "27017:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
      # volumes:
      #   - mongo-data:/data/db

    mongo-express:
      image: mongo-express:latest
      restart: always
      ports:
        - "8081:8081"
      depends_on:
        - mongodb
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb

